# Generated by Django 4.1.1 on 2022-10-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productup',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
