# Generated by Django 4.1.1 on 2022-10-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productup_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productup',
            name='catagory',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
