# Generated by Django 4.1.1 on 2022-10-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productup_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productup',
            name='specs',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
