# Generated by Django 4.1.1 on 2022-10-31 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productup_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productup',
            name='specs',
        ),
    ]
