# Generated by Django 4.1.1 on 2022-10-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productup_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_form',
            name='hashpass',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
