# Generated by Django 4.1.1 on 2022-11-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_register_form_hashpass'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprice', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productup')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.register_form')),
            ],
        ),
    ]
