# Generated by Django 4.1.1 on 2022-11-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='productup',
            name='fake_price',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
