# Generated by Django 4.1.1 on 2022-11-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productup_fake_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productup',
            name='specs1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productup',
            name='specs2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productup',
            name='specs3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productup',
            name='specs4',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productup',
            name='specs5',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
