# Generated by Django 4.1.1 on 2022-11-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productup_specs1_productup_specs2_productup_specs3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_tb',
            name='quantity',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
