# Generated by Django 4.1.1 on 2022-11-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cart_tb_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_tb',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
