# Generated by Django 4.1.1 on 2022-11-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='payment_tb',
        ),
    ]
