# Generated by Django 4.1.1 on 2022-11-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_payment_payment_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_tb',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
